; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "SolidWorks To URDF"
#define MyAppVersion "2026 v1.0.5"
#define MyAppPublisher "fish1sheep"
#define MyAppURL "http://wiki.ros.org/sw_urdf_exporter"

#define MainBinaryName  "SW2URDF.dll"
#define SetupBaseName   "sw2urdfSetup_"
#define DllLocation     AddBackslash(SourcePath + "..\SW2URDF\bin\x64\Release") + MainBinaryName
#define BuildVersion    GetVersionNumbersString(DllLocation)
#define CommitVersion   GetFileProductVersion(DllLocation)
#define AVF1            Copy(BuildVersion, 1, Pos(".", BuildVersion) - 1) + "_" + Copy(BuildVersion, Pos(".", BuildVersion) + 1)
#define AVF2            Copy(AVF1,       1, Pos(".", AVF1      ) - 1) + "_" + Copy(AVF1      , Pos(".", AVF1      ) + 1)
#define AppVersionFile  Copy(AVF2,       1, Pos(".", AVF2      ) - 1) + "_" + Copy(AVF2      , Pos(".", AVF2      ) + 1)

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E43E85A9-071D-430A-91B2-84B7AB923170}
AppName={#MyAppName}
WizardStyle=modern
AppVersion={#CommitVersion}
VersionInfoVersion={#BuildVersion}
VersionInfoCopyright=2019
VersionInfoProductName={#MyAppName}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
CreateAppDir=yes
OutputBaseFilename=sw2urdfSetup
;OutputBaseFilename={#SetupBaseName + AppVersionFile}
Compression=lzma                                                        
DefaultDirName="C:\Program Files\SolidWorks Corp\SolidWorks\URDFExporter"
SolidCompression=no
PrivilegesRequired=admin
OutputDir=..\..\INSTALL\OUTPUT
SourceDir=..\SW2URDF\bin\
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english";             MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified";   MessagesFile: "compiler:Languages\ChineseSimplified.isl"
Name: "japanese";            MessagesFile: "compiler:Languages\Japanese.isl"
Name: "german";              MessagesFile: "compiler:Languages\German.isl"

[CustomMessages]
; StatusMsg for [Run] - Registering controls
english.StatusRegistering=Registering controls ...
chinesesimplified.StatusRegistering=正在注册控件...
japanese.StatusRegistering=コントロールを登録しています...
german.StatusRegistering=Steuerelemente werden registriert ...

; StatusMsg for [UninstallRun] - Unregistering controls
english.StatusUnregistering=Unregistering controls ...
chinesesimplified.StatusUnregistering=正在注销控件...
japanese.StatusUnregistering=コントロールの登録を解除しています...
german.StatusUnregistering=Registrierung der Steuerelemente wird aufgehoben ...

; StatusMsg for [UninstallRun] - Cleaning up COM registration
english.StatusCleanupCOM=Cleaning up COM registration...
chinesesimplified.StatusCleanupCOM=正在清理 COM 注册...
japanese.StatusCleanupCOM=COM 登録をクリーンアップしています...
german.StatusCleanupCOM=COM-Registrierung wird bereinigt ...

[Files]
; 主插件 DLL 和所有依赖（RegAsm 注册时需要全部依赖，缺一不可）
Source: x64\Release\*.dll;    DestDir: {app}; Flags: ignoreversion; Check: IsWin64
Source: x64\Release\SW2URDF.tlb;    DestDir: {app}; Flags: ignoreversion; Check: IsWin64
Source: x64\Release\SW2URDF.png;    DestDir: {app}; Flags: ignoreversion; Check: IsWin64

; 图标文件
Source: x64\Release\images\*; DestDir: {app}\images; Flags: ignoreversion; Check: IsWin64

[Run]                                                        
Filename: "{reg:HKLM64\SOFTWARE\Microsoft\.NETFramework,InstallRoot}\v4.0.30319\RegAsm.exe"; Parameters: """{app}\SW2URDF.dll"" ""/codebase"""; StatusMsg: "{cm:StatusRegistering}"; Check: IsWin64


[Registry]
; SolidWorks 插件注册信息（安装时不创建，卸载时删除）
Root: HKLM64; Subkey: "SOFTWARE\SolidWorks\Addins\65c9fc17-6a74-45a3-8f84-55185900275d";        ValueType: none; ValueName: ""; Flags: dontcreatekey deletekey uninsdeletevalue; Check: IsWin64
Root: HKCU64; Subkey: "Software\SolidWorks\AddInsStartup\65c9fc17-6a74-45a3-8f84-55185900275d"; ValueType: none; ValueName: ""; Flags: dontcreatekey deletekey uninsdeletevalue; Check: IsWin64

[UninstallRun]
; 正常 .NET COM 反注册
Filename: "{reg:HKLM64\SOFTWARE\Microsoft\.NETFramework,InstallRoot}\v4.0.30319\RegAsm.exe"; Parameters:  """{app}\SW2URDF.dll"" ""/unregister"""; StatusMsg: "{cm:StatusUnregistering}"; Check: IsWin64; RunOnceId: "UnregisterSW2URDF"
; 强制清除 COM CLSID 注册表残留（即使 RegAsm 失败也能清理干净）
Filename: "reg.exe"; Parameters: "delete ""HKLM\SOFTWARE\Classes\CLSID\{{65c9fc17-6a74-45a3-8f84-55185900275d}}"" /f"; StatusMsg: "{cm:StatusCleanupCOM}"; Check: IsWin64; RunOnceId: "DeleteCLSID"
