; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "SolidWorks To URDF"
#define MyAppVersion "2018 v1.6"
#define MyAppPublisher "Stephen Brawner"
#define MyAppURL "http://wiki.ros.org/sw_urdf_exporter"

#define MainBinaryName  "SW2URDF.dll"
#define SetupBaseName   "sw2urdfSetup_"
#define DllLocation     AddBackslash(SourcePath + "..\SW2URDF\bin\x64\Release") + MainBinaryName
#define BuildVersion    GetVersionNumbersString(DllLocation)
#define CommitVersion   GetFileProductVersion(DllLocation)
#define AVF1            Copy(BuildVersion, 1, Pos(".", BuildVersion) - 1) + "_" + Copy(BuildVersion, Pos(".", BuildVersion) + 1)
#define AVF2            Copy(AVF1,       1, Pos(".", AVF1      ) - 1) + "_" + Copy(AVF1      , Pos(".", AVF1      ) + 1)
#define AppVersionFile  Copy(AVF2,       1, Pos(".", AVF2      ) - 1) + "_" + Copy(AVF2      , Pos(".", AVF2      ) + 1)

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E43E85A9-071D-430A-91B2-84B7AB923170}
AppName={#MyAppName}
AppVersion={#CommitVersion}
VersionInfoVersion={#BuildVersion}
VersionInfoCopyright=2019
VersionInfoProductName={#MyAppName}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
CreateAppDir=yes
OutputBaseFilename=sw2urdfSetup
;OutputBaseFilename={#SetupBaseName + AppVersionFile}
Compression=lzma                                                        
DefaultDirName="C:\Program Files\SolidWorks Corp\SolidWorks\URDFExporter"
SolidCompression=no
PrivilegesRequired=admin
OutputDir=..\..\INSTALL\OUTPUT
SourceDir=..\SW2URDF\bin\
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; 主插件 DLL 和 COM 类型库
Source: x64\Release\SW2URDF.dll;    DestDir: {app}; Flags: ignoreversion; Check: IsWin64
Source: x64\Release\SW2URDF.tlb;    DestDir: {app}; Flags: ignoreversion; Check: IsWin64
Source: x64\Release\SW2URDF.png;    DestDir: {app}; Flags: ignoreversion; Check: IsWin64

; SolidWorks 工具库（SW2URDF 依赖）
Source: x64\Release\solidworkstools.dll; DestDir: {app}; Flags: ignoreversion; Check: IsWin64

; 日志库
Source: x64\Release\log4net.dll;     DestDir: {app}; Flags: ignoreversion; Check: IsWin64

; 数学运算库（坐标变换、惯性计算）
Source: x64\Release\MathNet.Numerics.dll; DestDir: {app}; Flags: ignoreversion; Check: IsWin64

; CSV 解析库（CSV 导入导出）
Source: x64\Release\CsvHelper.dll;   DestDir: {app}; Flags: ignoreversion; Check: IsWin64

; CsvHelper 的传递依赖
Source: x64\Release\System.Runtime.CompilerServices.Unsafe.dll; DestDir: {app}; Flags: ignoreversion; Check: IsWin64
Source: x64\Release\System.Threading.Tasks.Extensions.dll;       DestDir: {app}; Flags: ignoreversion; Check: IsWin64

[Run]                                                        
Filename: "{reg:HKLM64\SOFTWARE\Microsoft\.NETFramework,InstallRoot}\v4.0.30319\RegAsm.exe"; Parameters: """{app}\SW2URDF.dll"" ""/codebase"""; StatusMsg: Registering controls ...; Check: IsWin64; Languages:


[Registry]
Root: HKLM64; Subkey: "SOFTWARE\SolidWorks\Addins\65c9fc17-6a74-45a3-8f84-55185900275d";        ValueType: none; ValueName: ""; Flags: dontcreatekey deletekey uninsdeletevalue; Check: IsWin64
Root: HKCU64; Subkey: "Software\SolidWorks\AddInsStartup\65c9fc17-6a74-45a3-8f84-55185900275d"; ValueType: none; ValueName: ""; Flags: dontcreatekey deletekey uninsdeletevalue; Check: IsWin64

[UninstallRun]
Filename: "{reg:HKLM64\SOFTWARE\Microsoft\.NETFramework,InstallRoot}\v4.0.30319\RegAsm.exe"; Parameters:  """{app}\SW2URDF.dll"" ""/unregister"""; StatusMsg: Unregistering controls ...; Check: IsWin64; Languages: ; RunOnceId: "UnregisterSW2URDF"
